### ISSUE TITLE
[Bug] Version 0.13.0 breaks dependencies optimizer

### ISSUE THREAD

**Issue by fabiiomiiguel** [electron-vite/vite-plugin-electron-renderer#35]
Hello, the last version `0.13.0` breaks my project and gives this error:

<details>
  <summary>npm run dev</summary>

    > electron-vue-vite@0.0.1 dev
    > vite
    
    
      VITE v4.2.0  ready in 308 ms
    
      ➜  Local:   http://localhost:5173/
      ➜  Network: use --host to expose
      ➜  press h to show help
    vite v4.2.0 building for development...
    
    watching for file changes...
    vite v4.2.0 building for development...
    
    watching for file changes...
    Can not resolve path: /Users/fabio/Projects/dev/electron/node_modules/set-interval-async/dynamic
    
    build started...
    
    build started... (x2)
    Can not resolve path: /Users/fabio/Projects/dev/electron/node_modules/virtual-module:/Users/fabio/Projects/dev/electron/src/App.vue?id=0
    ✘ [ERROR] Could not resolve "virtual-module:/Users/fabio/Projects/dev/electron/src/App.vue?id=0"
    
    ✓ 1 modules transformed.
    ✓ 1 modules transformed. (x2)
    Error:   Failed to scan for dependencies from entries:
      /Users/fabio/Projects/dev/electron/index.html
    /Users/fabio/Projects/dev/electron/worker.html
    
      ✘ [ERROR] Build failed with 1 error:
    error: Could not resolve "virtual-module:/Users/fabio/Projects/dev/electron/src/App.vue?id=0" [plugin vite-plugin-target:optimizer:esbuild]
    
        html:/Users/fabio/Projects/dev/electron/src/App.vue:1:14:
          1 │ export * from "virtual-module:/Users/fabio/Projects/dev/electron/sr...
            ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      This error came from the "onLoad" callback registered here:
    
        node_modules/vite-plugin-electron-renderer/index.js:284:12:
          284 │       build.onLoad({
              ╵             ~~~~~~
    
        at setup (/Users/fabio/Projects/dev/electron/node_modules/vite-plugin-electron-renderer/index.js:284:13)
        at handlePlugins (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1279:21)
        at buildOrContextImpl (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:968:5)
        at Object.buildOrContext (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:776:5)
        at /Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2172:68
        at new Promise (<anonymous>)
        at Object.context (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2172:27)
        at Object.context (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2012:58)
        at prepareEsbuildScanner (file:///Users/fabio/Projects/dev/electron/node_modules/vite/dist/node/chunks/dep-c167897e.js:43542:26)
    
    
        at failureErrorWithLog (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1636:15)
        at /Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1048:25
        at runOnEndCallbacks (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1471:45)
        at buildResponseToResult (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1046:7)
        at /Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1058:9
        at new Promise (<anonymous>)
        at requestCallbacks.on-end (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1057:54)
        at handleRequest (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:723:19)
        at handleIncomingPacket (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:745:7)
        at Socket.readFromStdout (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:673:7)
    dist-electron/preload/index.js  7.49 kB │ gzip: 3.26 kB │ map: 3.93 kB
    built in 88ms.
    dist-electron/main/index.js  2.81 kB │ gzip: 1.12 kB │ map: 5.96 kB
    built in 88ms.
    Can not resolve path: /Users/fabio/Projects/dev/electron/node_modules/@oruga-ui_oruga-next
    Can not resolve path: /Users/fabio/Projects/dev/electron/node_modules/set-interval-async_dynamic
    ✘ [ERROR] Could not resolve "set-interval-async_dynamic"
    
    ✘ [ERROR] Could not resolve "@oruga-ui_oruga-next"
    
    ✘ [ERROR] Build failed with 1 error:
    error: Could not resolve "set-interval-async_dynamic" [plugin vite-plugin-target:optimizer:esbuild]
    
      This error came from the "onLoad" callback registered here:
    
        node_modules/vite-plugin-electron-renderer/index.js:284:12:
          284 │       build.onLoad({
              ╵             ~~~~~~
    
        at setup (/Users/fabio/Projects/dev/electron/node_modules/vite-plugin-electron-renderer/index.js:284:13)
        at handlePlugins (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1279:21)
        at buildOrContextImpl (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:968:5)
        at Object.buildOrContext (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:776:5)
        at /Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2172:68
        at new Promise (<anonymous>)
        at Object.context (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2172:27)
        at Object.context (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2012:58)
        at prepareEsbuildOptimizerRun (file:///Users/fabio/Projects/dev/electron/node_modules/vite/dist/node/chunks/dep-c167897e.js:44825:35)
    
    ✘ [ERROR] Build failed with 1 error:
    error: Could not resolve "@oruga-ui_oruga-next" [plugin vite-plugin-target:optimizer:esbuild]
    
      This error came from the "onLoad" callback registered here:
    
        node_modules/vite-plugin-electron-renderer/index.js:284:12:
          284 │       build.onLoad({
              ╵             ~~~~~~
    
        at setup (/Users/fabio/Projects/dev/electron/node_modules/vite-plugin-electron-renderer/index.js:284:13)
        at handlePlugins (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1279:21)
        at buildOrContextImpl (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:968:5)
        at Object.buildOrContext (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:776:5)
        at /Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2172:68
        at new Promise (<anonymous>)
        at Object.context (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2172:27)
        at Object.context (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:2012:58)
        at prepareEsbuildOptimizerRun (file:///Users/fabio/Projects/dev/electron/node_modules/vite/dist/node/chunks/dep-c167897e.js:44825:35)
    
    11:33:29 AM [vite] error while updating dependencies:
    Error: Build failed with 2 errors:
    error: Build failed with 1 error:
    error: Could not resolve "set-interval-async_dynamic"
    error: Build failed with 1 error:
    error: Could not resolve "@oruga-ui_oruga-next"
        at failureErrorWithLog (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1636:15)
        at /Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1048:25
        at runOnEndCallbacks (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1471:45)
        at buildResponseToResult (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1046:7)
        at /Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1058:9
        at new Promise (<anonymous>)
        at requestCallbacks.on-end (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:1057:54)
        at handleRequest (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:723:19)
        at handleIncomingPacket (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:745:7)
        at Socket.readFromStdout (/Users/fabio/Projects/dev/electron/node_modules/esbuild/lib/main.js:673:7)
</details>

With the previous version `0.12.1` everything works fine.

**Comment by caoxiemeihao** [comment]
Oh! can you provide a minimal reproduction repo?

**Comment by aphex** [comment]
I am having a similar issue on windows the optimizer is breaking my build as well. 

It's trying to find `node_modules` in the wrong path. for example the error is
`Can not resolve path: F:\path\to\monorepo\project\packages\foo\node_modules\zod`

However zod is not going to be there as I am using `pnpm` and another package within the workspace is handling zod.

I am also getting all kinds of errors trying to optimize `.html` files. For reference the `id` here https://github.com/electron-vite/vite-plugin-electron-renderer/blob/f20581ed36150ee1c27a93e12ba374a15254fcfd/src/optimizer.ts#L82 is a file path ending in `.html`. It seemed to even be finding `.html` files from the `release` folder in the root of this pacakge. I  am not sure why it was even looking in there. On windows it also seems to be doubling up paths I am seeing this error as well
`Can not resolve path: F:\path\to\monorepo\project\packages\foo\node_modules\F:\path\to\monorepo\project\packages\foo\index.html`

Adding a `return` here https://github.com/electron-vite/vite-plugin-electron-renderer/blob/main/src/optimizer.ts#L81 gets me back to building.

Or simply commenting out the whole optimizer step here https://github.com/electron-vite/vite-plugin-electron-renderer/blob/f20581ed36150ee1c27a93e12ba374a15254fcfd/src/index.ts#L27 will get it back to running.

For now I think I just need to roll back to 0.12.1 I don't see any way to opt out of this optimizer stuff.

**Comment by fabiiomiiguel** [comment]
Thank you, this version fixed everything from my side 🙂

**Comment by fabiiomiiguel** [comment]
So this version creates a new bug.


<details>
  <summary>npm run dev</summary>

  ```
  runtime-core.esm-bundler.js:3002 Uncaught TypeError: Cannot read properties of null (reading 'isCE')
      at renderSlot (runtime-core.esm-bundler.js:3002:34)
      at Button-c75f7992.mjs:190:9
      at normalizeChildren (runtime-core.esm-bundler.js:7025:42)
      at createBaseVNode (runtime-core.esm-bundler.js:6773:9)
      at _createVNode (runtime-core.esm-bundler.js:6875:12)
      at createVNodeWithArgsTransform (runtime-core.esm-bundler.js:6730:12)
      at createBlock (runtime-core.esm-bundler.js:6701:23)
      at Proxy.render5 (Button-c75f7992.mjs:171:23)
      at renderComponentRoot (/Users/fabio/Projects/dev/electron/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:906:44)
      at ReactiveEffect.componentUpdateFn [as fn] (/Users/fabio/Projects/dev/electron/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5587:57)
  ```
  
</details>

I tried some solutions from here `https://github.com/vuejs/core/issues/4344` but didn't work.

I updated this https://github.com/fabiiomiiguel/-vite-plugin-electron-renderer so if you want, you can give a look at the issue.

Thank you in advance 😁

**Comment by caoxiemeihao** [comment]
`v0.13.2` is out!

**Comment by fabiiomiiguel** [comment]
Wow so fast! Sadly that brings a new error again 😔

<details>
  <summary>npm run dev</summary>

```
✘ [ERROR] Cannot find module '@oruga-ui_oruga-next'
Require stack:
- /Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/vite-plugin-electron-renderer/index.js [plugin vite-plugin-target:optimizer:esbuild]

  This error came from the "onLoad" callback registered here:

    node_modules/vite-plugin-electron-renderer/index.js:259:12:
      259 │       build.onLoad({
          ╵             ~~~~~~

    at setup (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/vite-plugin-electron-renderer/index.js:259:13)
    at handlePlugins (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:776:5)
    at /Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:2172:27)
    at Object.context (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:2012:58)
    at prepareEsbuildOptimizerRun (file:///Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/vite/dist/node/chunks/dep-79892de8.js:44840:35)

12:32:21 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
error: Cannot find module '@oruga-ui_oruga-next'
Require stack:
- /Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/vite-plugin-electron-renderer/index.js
    at failureErrorWithLog (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/Users/fabio/Projects/-vite-plugin-electron-renderer/node_modules/esbuild/lib/main.js:673:7)
```

</details>

**Comment by caoxiemeihao** [comment]
Wow I has tested `v0.13.2` on my local is well 😅

**Comment by caoxiemeihao** [comment]
`v0.13.3` is out! 🔥

**Comment by fabiiomiiguel** [comment]
What a legend! I can confirm now everything works! Thank you and sorry to bother so much.
