### ISSUE TITLE
Can not resolve path: node_modules/.pnpm/nuxt@3.2.2_@types+node@18.14.0/node_modules/nuxt/dist/app/entry.mjs

### ISSUE THREAD

**Issue by OyewoleOyedeji** [electron-vite/vite-plugin-electron-renderer#40]
Nuxt project info

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.7.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.29.1`
- Builder:          `vite`
- User Config:      `modules`, `app`, `ssr`, `tailwindcss`, `fonty`, `electron`, `colorMode`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.1`, `@vueuse/nuxt@9.13.0`, `nuxt-fonty@1.0.0`, `nuxt-electron@0.4.2`, `@nuxtjs/color-mode@3.2.0`
- Build Modules:    `-`
------------------------------

`nuxt.config.ts`

```ts
export default defineNuxtConfig({
  // ... other configurations
  electron: {
    outDir: "out",
    renderer: {
      nodeIntegration: true,
    },
  },
});
```

Error:

```log
Nuxi 3.2.2                                                                                                                                16:31:26
                                                                                                                                          16:31:26
  > Local:    http://localhost:3000/

i nuxt.config.ts updated. Restarting nuxt...                                                                                              16:32:18
i Using default Tailwind CSS file from runtime/tailwind.css                                                              nuxt:tailwindcss 16:32:18
i Tailwind Viewer: http://localhost:3000/_tailwind/                                                                      nuxt:tailwindcss 16:32:18
[write] 16:32:19 out\main.js                                                                                                              16:32:19
[write] 16:32:19 out\preload.js                                                                                                           16:32:19

[6068:0321/163219.757:ERROR:network_change_notifier_win.cc(222)] WSALookupServiceBegin failed with: 0
Can not resolve path: D:\Documents\GitHub\Projects\javabattery\node_modules\D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\nuxt@3.2.2_@types+node@18.14.0\node_modules\nuxt\dist\app\entry.mjs
✘ [ERROR] [19072:0321/163220.290:ERROR:network_change_notifier_win.cc(222)] WSALookupServiceBegin failed with: 0
[plugin vite-plugin-target:optimizer:esbuild] ENOENT: no such file or directory, mkdir 'D:\Documents\GitHub\Projects\javabattery\node_modules\.vite-electron-renderer\D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\nuxt@3.2.2_@types+node@18.14.0\node_modules\nuxt\dist\app\entry.mjs'

    node_modules/.pnpm/vite-plugin-electron-renderer@0.13.0/node_modules/vite-plugin-electron-renderer/index.js:13:7:
      13 │     fs.mkdirSync(dir, { recursive: true });
         ╵        ^

    at Object.mkdirSync (node:fs:1382:3)
    at ensureDir (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\vite-plugin-electron-renderer@0.13.0\node_modules\vite-plugin-electron-renderer\index.js:13:8)
    at D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\vite-plugin-electron-renderer@0.13.0\node_modules\vite-plugin-electron-renderer\index.js:289:9
    at requestCallbacks.on-load (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1426:28)
    at handleRequest (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:727:19)
    at handleIncomingPacket (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:749:7)
    at Socket.readFromStdout (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:512:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  This error came from the "onLoad" callback registered here:

    node_modules/.pnpm/vite-plugin-electron-renderer@0.13.0/node_modules/vite-plugin-electron-renderer/index.js:284:12:
      284 │       build.onLoad({
          ╵             ~~~~~~

    at setup (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\vite-plugin-electron-renderer@0.13.0\node_modules\vite-plugin-electron-renderer\index.js:284:13)
    at handlePlugins (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1287:21)
    at buildOrServeImpl (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:974:5)
    at Object.buildOrServe (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:780:5)
    at D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:2131:14)
    at build (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1978:51)
    at scanImports (file:///D:/Documents/GitHub/Projects/javabattery/node_modules/.pnpm/vite@4.1.2_@types+node@18.14.0/node_modules/vite/dist/node/chunks/dep-9912c491.js:41762:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async discoverProjectDependencies (file:///D:/Documents/GitHub/Projects/javabattery/node_modules/.pnpm/vite@4.1.2_@types+node@18.14.0/node_modules/vite/dist/node/chunks/dep-9912c491.js:42801:31)
    at async Timeout._onTimeout (file:///D:/Documents/GitHub/Projects/javabattery/node_modules/.pnpm/vite@4.1.2_@types+node@18.14.0/node_modules/vite/dist/node/chunks/dep-9912c491.js:42250:38)

  The plugin "vite-plugin-target:optimizer:esbuild" was triggered by this import

    <stdin>:1:7:
      1 │ import "D:/Documents/GitHub/Projects/javabattery/node_modules/.pnpm/nuxt@3.2.2_@types+node@18.14.0/node_modules/nuxt/dist/app/entry.mjs"
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


 ERROR  Build failed with 1 error:                                                                                                        16:32:21
node_modules/.pnpm/vite-plugin-electron-renderer@0.13.0/node_modules/vite-plugin-electron-renderer/index.js:13:7: ERROR: [plugin: vite-plugin-target:optimizer:esbuild] ENOENT: no such file or directory, mkdir 'D:\Documents\GitHub\Projects\javabattery\node_modules\.vite-electron-renderer\D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\nuxt@3.2.2_@types+node@18.14.0\node_modules\nuxt\dist\app\entry.mjs'

Can not resolve path: D:\Documents\GitHub\Projects\javabattery\node_modules\@headlessui_vue                                               16:32:42
✘ [ERROR] Could not resolve "@headlessui_vue"

✘ [ERROR] [plugin vite-plugin-target:optimizer:esbuild] Build failed with 1 error:
error: Could not resolve "@headlessui_vue"

  This error came from the "onLoad" callback registered here:

    node_modules/.pnpm/vite-plugin-electron-renderer@0.13.0/node_modules/vite-plugin-electron-renderer/index.js:284:12:
      284 │       build.onLoad({
          ╵             ~~~~~~

    at setup (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\vite-plugin-electron-renderer@0.13.0\node_modules\vite-plugin-electron-renderer\index.js:284:13)
    at handlePlugins (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1287:21)
    at buildOrServeImpl (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:974:5)
    at Object.buildOrServe (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:780:5)
    at D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:2131:14)
    at build (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1978:51)
    at runOptimizeDeps (file:///D:/Documents/GitHub/Projects/javabattery/node_modules/.pnpm/vite@4.1.2_@types+node@18.14.0/node_modules/vite/dist/node/chunks/dep-9912c491.js:42943:26)
    at async optimizeNewDeps (file:///D:/Documents/GitHub/Projects/javabattery/node_modules/.pnpm/vite@4.1.2_@types+node@18.14.0/node_modules/vite/dist/node/chunks/dep-9912c491.js:42301:16)
    at async runOptimizer (file:///D:/Documents/GitHub/Projects/javabattery/node_modules/.pnpm/vite@4.1.2_@types+node@18.14.0/node_modules/vite/dist/node/chunks/dep-9912c491.js:42330:55)


 ERROR  16:32:42 [vite] error while updating dependencies:                                                                                16:32:42
Error: Build failed with 1 error:
error: Build failed with 1 error:
error: Could not resolve "@headlessui_vue"
    at failureErrorWithLog (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1604:15)
    at D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1056:28
    at runOnEndCallbacks (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1476:61)
    at buildResponseToResult (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1054:7)
    at D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:1166:14
    at responseCallbacks.<computed> (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:701:9)
    at handleIncomingPacket (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:756:9)
    at Socket.readFromStdout (D:\Documents\GitHub\Projects\javabattery\node_modules\.pnpm\esbuild@0.16.17\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:512:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by caoxiemeihao** [comment]
Upgrade to `v0.13.4`

**Comment by OyewoleOyedeji** [comment]
@caoxiemeihao
I no more experience the error but a new error has surfaced when I try to do this

```vue
<script setup lang="ts">
import { shell } from "electron";
</script>
```

```log
 ERROR  Failed to load url vite-plugin-electron-renderer/builtins/electron (resolved id: vite-plugin-electron-renderer/builtins/electron) in D:/Documents/GitHub/Projects/javabattery/app.vue. Does the file exist?
```

**Comment by caoxiemeihao** [comment]
Try upgrade `v0.13.6` to resolve it?

**Comment by OyewoleOyedeji** [comment]
The error still persists

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by OyewoleOyedeji** [comment]
@caoxiemeihao  I made a Codespace instead:
<https://oyewoleoyedeji-probable-adventure-vrqxqg4vrjqhpggj.github.dev>

**Comment by caoxiemeihao** [comment]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/26263658/227669551-698a627f-83a9-4611-ab6e-584d6c96cab8.png">

**Comment by OyewoleOyedeji** [comment]
Okay I've exported the codespace to a repository

<https://github.com/OyewoleOyedeji/vite-plugin-electron-renderer-bug-reproduction>

**Comment by OyewoleOyedeji** [comment]
@caoxiemeihao I have update to `0.13.10`, I have this new error

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

I checked the network tab in the Chrome Devtools and for some reason the electron module was being loaded as a page 🤔

**Comment by caoxiemeihao** [comment]
1. Upgrade `vite-plugin-electron-renderer` to `0.13.11`

2. `electron/main.ts`

```diff
const createWindow = () => {
  const window = new BrowserWindow({
    webPreferences: {
      preload: join(__dirname, "../out/preload.js"),
+     contextIsolation: false,
      nodeIntegration: true,
    },
  });
  window.loadURL(process.env.VITE_DEV_SERVER_URL);
};
```

**Comment by OyewoleOyedeji** [comment]
@caoxiemeihao 
I found the problem I had, my actual project which I used the module for didn't have a `builtins` folder but the reproduction folder had the folder which was able to be resolved

**Comment by caoxiemeihao** [comment]
> I found the problem I had, my actual project which I used the module for didn't have a `builtins` folder

The `builtins` aways generated in my local machine and use node19.
BTW, If you have an error there that prevents generating `builtins`, you can also manual execute the script.

```sh
node node_modules/vite-plugin-electron-renderer/install.mjs
```
