### ISSUE TITLE
0.14.4 broke my build

### ISSUE THREAD

**Issue by Stanzilla** [electron-vite/vite-plugin-electron-renderer#73]
Hey there, I don't know why exactly but the update broke my build, see here https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5047264176/jobs/9053884886?pr=1891

```
vite v4.3.8 building for production...
transforming...
✓ 1 modules transformed.
rendering chunks...
computing gzip size...
dist-electron/preload/index.js  1.57 kB │ gzip: 0.76 kB
Binding arguments in strict mode (Note that you need plugins to import files that are not JavaScript)
file: /home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/.vite-electron-renderer/archiver.mjs:4:13
2: export const length = _M_.length;
3: export const name = _M_.name;
4: export const arguments = _M_.arguments;
                ^
5: export const caller = _M_.caller;
6: export const prototype = _M_.prototype;
error during build:
RollupError: Binding arguments in strict mode (Note that you need plugins to import files that are not JavaScript)
    at error (file:///home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/rollup/dist/es/shared/node-entry.js:2125:[30](https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5047264176/jobs/9053884886?pr=1891#step:7:31))
    at Module.error (file:///home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/rollup/dist/es/shared/node-entry.js:1[34](https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5047264176/jobs/9053884886?pr=1891#step:7:35)38:16)
    at Module.tryParse (file:///home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/rollup/dist/es/shared/node-entry.js:14145:25)
    at Module.setSource (file:///home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/rollup/dist/es/shared/node-entry.js:1[37](https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5047264176/jobs/9053884886?pr=1891#step:7:38)47:[39](https://github.com/WeakAuras/WeakAuras-Companion/actions/runs/5047264176/jobs/9053884886?pr=1891#step:7:40))
    at ModuleLoader.addModuleSource (file:///home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/rollup/dist/es/shared/node-entry.js:23712:20)
✓ built in 37ms
Error: Process completed with exit code 1.
```

**Comment by Stanzilla** [comment]
I also see this when running in dev: 

![image](https://github.com/electron-vite/vite-plugin-electron-renderer/assets/75278/6adff63e-b0e1-4c7b-a88c-573735969045)


which looks like a path issue

**Comment by caoxiemeihao** [comment]
👋 fixed 😂
https://github.com/caoxiemeihao/lib-esm/commit/0cc3de0dfa392e264074fe87273aa0898f7d738a
https://github.com/electron-vite/vite-plugin-electron-renderer/pull/74/commits/46def0c1fd77423b942d62cd0c5ef63d76f917eb

**Comment by Stanzilla** [comment]
Thank you!

**Comment by caoxiemeihao** [comment]
Is okay now :)

**Comment by Stanzilla** [comment]
Yes, looks like it! Thanks again
