### ISSUE TITLE
引用 fs-extra 库报错

### ISSUE THREAD

**Issue by songyihong** [electron-vite/vite-plugin-electron-renderer#75]
在你项目的引入库 ```fs-extra```
然后 examples/quick-start/renderer/samples/index.ts 文件增加如下代码

```ts
import fs from 'fs-extra'

console.log(fs)
```

然后启动 ```run dev``` 在控制台报如下错误

```js
aceful-fs.js:52 Uncaught TypeError: Cannot set property close of #<Object> which has only a getter
    at ../../node_modules/.pnpm/graceful-fs@4.2.10/node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:52:6)
    at __require2 (chunk-DTF2DXDB.js?v=fd5ed1e5:18:50)
    at ../../node_modules/.pnpm/fs-extra@11.1.1/node_modules/fs-extra/lib/fs/index.js (index.js:5:12)
    at __require2 (chunk-DTF2DXDB.js?v=fd5ed1e5:18:50)
    at ../../node_modules/.pnpm/fs-extra@11.1.1/node_modules/fs-extra/lib/index.js (index.js:5:6)
    at __require2 (chunk-DTF2DXDB.js?v=fd5ed1e5:18:50)
    at index.js:16:1
````

**Comment by caoxiemeihao** [comment]
> Uncaught TypeError: Cannot set property close of #<Object> which has only a getter

这个报错来自 esbuild 转换代码时候烦人的包装导致的，Vite 默认的预构建强依赖 esbuild 就是这么反人类。

推荐解决方案：

```ts
renderer({
  resolve: {
   'fs-extra': { type: 'cjs' },
  },
})
```
